version: '3.1'
services:
  server:
    image: refcode_api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   -./:/app
    ports:
      - 5000:5000
    networks:
      - dev-networks
    # depends_on:
    #   - rabbitmq
    command: ./build/refcode_api server
  worker:
    image: refcode_api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   -./:/app
    ports:
      - 5000:5000
    networks:
      - dev-networks
    # depends_on:
    #   - rabbitmq
    command: ./build/refcode_api worker
# networks:
#   dev-networks: